version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Build started on `date`
  build:
    commands:
      - echo Copying website files to S3 bucket
      - aws s3 sync . s3://korigichuki.me --delete --exclude "buildspec.yml" --exclude ".git/*"
      - echo Invalidating CloudFront cache
      - aws cloudfront create-invalidation --distribution-id E1YKID81ICNHZ --paths "/*"
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  exclude-paths:
    - buildspec.yml
    - .git/**/*
